# Generated by Django 5.2.9 on 2025-12-10 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("etl_jobs", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="pipeline",
            name="destination_database",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="pipeline",
            name="source_database",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
