# Generated by Django 5.2.9 on 2025-12-10 16:36

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('etl_jobs', '0002_pipeline_destination_database_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pipeline',
            name='source_aggregation_query',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.JSONField(), blank=True, help_text='Aggregation pipeline as a list of MongoDB aggregation stages', null=True, size=None),
        ),
    ]
